import { ApplicationState } from "../../../../../State";
import { EthAddress, uint256 } from "../../../../../utils/types";
export declare function updateDilutionState(appState1: ApplicationState, force?: boolean): Promise<{
    createdTime: number;
    walletState: import("../../../../../State").WalletState;
    smartWalletState: import("../../../../../State").SmartWalletState;
    tokenPrice: Map<EthAddress, uint256>;
    NFTSellingState: import("../../../../../State").NFTSellingState;
    NFTAuctioningState: import("../../../../../State").NFTAuctioningState;
    NFTVeTravaMarketSellingState: import("../../../../../State").NFTVeTravaSellingState;
    TravaGovernanceState: import("../../../../../State").TravaGovernanceState;
    ExpeditionState: import("../../../../../State").ExpeditionState;
    DilutionState: import("../../../../../State").DilutionState;
    forkCompoundLPState: import("../../../../../State").ForkedCompoundLPState;
    forkAaveLPState: import("../../../../../State").ForkedAaveLPState;
    pancakeSwapV2Pair: import("../../../../../State").PancakeSwapV2Pair;
    cs251state: import("../../../../../State").cs251state;
    PancakeFarmState: import("../../../../../State").PancakeFarmState;
    web3: import("ethers").JsonRpcProvider;
    chainId: number | string;
    simulatorUrl: string;
}>;
